import { MatchComponent } from '../pages/round/match/match.component';
// Generated by https://quicktype.io

export interface Tournament {
  name:   string;
  date:   string;
  region: string;
}

export interface TournamentResponse {
  tournament: {Date: number;
  TournamentName: string;
  Municipio: string;
  Provincia: string;}
}
export interface TournamentSearchData {
  name:   string;
  region: string;
  date:   string;
  winner: string;
  mostUsedArchetype: string;
}

export interface TournamentInfo{
  TournamentDate: string;
  TournamentLocation: string;
  AmountOfPlayers: number;
  State: string;

  Matchs: Match[];
  ParticipantsID: string[];
}

export interface Match
{
  Player1: string;
  Player2: string;
  Player1Score: number;
  Player2Score: number;
}
