// Generated by https://quicktype.io

export interface Tournament {
  name:   string;
  date:   string;
  region: string;
}

export interface TournamentSearchData {
  name:   string;
  region: string;
  date:   string;
  winner: string;
  mostUsedArchetype: string;
}
