export interface UserSearchData {
  name:   string;
  region: string;
  town: string;
  decksAmount: number;
  amountOfTournamentsParticipated: number;
  amountOfTournamentsWinned: number;
}

// Generated by https://quicktype.io

export interface UserData {
  id:            string;
  mydecks:       MyDeck[];
  myTournaments: MyTournament[];
}

export interface MyTournament {
  name:   string;
  date:   string;
  region: string;
}

export interface MyDeck {
  id:        number;
  name:      string;
  attribute: string;
  user_id:   number;
}

//TEMPORAL
export interface PlayersResponse {
  data: {
    players: Player[];
  };
}

export interface Player {
  PlayerName: string;
  PlayerPassword: string;
  Roll: string;
}


